## 智慧預警 - 透過隨機森林找出危機公司

In [1]:
# 讀取 CSV File
import pandas as pd # 引用套件並縮寫為 pd
df = pd.read_csv('data/xgboost.csv')

In [2]:
df.head(10)

,公司,PRO/NNOR (5),PRO/NNOR (4),PRO/NNOR (3),PRO/NNOR (2),PRO/NNOR (1),PRO/NNOR (0),dangerous
0,1103 嘉泥,0.2182,0.1638,0.2493,0.2410,0.2360,0.2651,0
1,1109 信大,0.3982,0.3820,0.3651,0.3477,0.3261,0.2701,0
2,1109 信大,0.2701,0.2912,0.2734,0.2031,0.1357,0.2362,0
3,1109 信大,0.2912,0.2734,0.2031,0.1357,0.2362,0.2476,0
4,1109 信大,0.2734,0.2031,0.1357,0.2362,0.2476,0.2832,0
5,1109 信大,0.2031,0.1357,0.2362,0.2476,0.2832,0.2612,0
6,1113 永康,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1
7,1203 味王,0.2363,0.2199,0.2178,0.2091,0.2354,0.2603,1
8,1206 台鳳,0.1451,0.1288,0.1196,0.1133,0.1989,0.1291,1
9,1206 台鳳,0.1196,0.1133,0.1989,0.1291,0.1439,0.0268,1

In [3]:
X = df[['公司', 'PRO/NNOR (5)', 'PRO/NNOR (4)', 'PRO/NNOR (3)', 'PRO/NNOR (2)', 'PRO/NNOR (1)', 'PRO/NNOR (0)']]
y = df['dangerous']

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [6]:
X_train.head(10)

,公司,PRO/NNOR (5),PRO/NNOR (4),PRO/NNOR (3),PRO/NNOR (2),PRO/NNOR (1),PRO/NNOR (0)
224,2024 志聯,0.0344,-0.0359,0.0425,0.0419,0.1218,0.0407
276,2348 海悅,0.0210,0.0046,0.0037,0.0085,0.0143,0.0160
131,1606 歌林,0.0872,0.0000,0.0000,0.0000,0.0000,0.0000
284,2358 廷鑫,0.0689,0.0099,0.0287,0.0527,0.0419,0.0345
148,1613 台一,-0.0522,-0.0188,0.0288,0.0323,0.0261,0.0245
223,2024 志聯,0.0455,0.0344,-0.0359,0.0425,0.0419,0.1218
15,1215 卜蜂,0.0850,0.0853,0.0759,0.0681,0.0662,0.0466
631,9922 優美,0.3372,0.3472,0.3788,0.2838,0.2948,0.2679
504,3055 蔚華科,0.2129,0.1749,0.2434,0.2202,0.2123,0.2186
385,2528 皇普,0.0784,-0.0089,-0.2586,-0.5447,-0.5003,-0.8267

In [7]:
X_train_NoName = X_train[['PRO/NNOR (5)', 'PRO/NNOR (4)', 'PRO/NNOR (3)', 'PRO/NNOR (2)', 'PRO/NNOR (1)', 'PRO/NNOR (0)']]

In [8]:
X_train_NoName.head(3)

,PRO/NNOR (5),PRO/NNOR (4),PRO/NNOR (3),PRO/NNOR (2),PRO/NNOR (1),PRO/NNOR (0)
224,0.0344,-0.0359,0.0425,0.0419,0.1218,0.0407
276,0.0210,0.0046,0.0037,0.0085,0.0143,0.0160
131,0.0872,0.0000,0.0000,0.0000,0.0000,0.0000

In [9]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(max_depth = 3, n_estimators = 10)
rfc.fit(X_train_NoName, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=3, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [10]:
X_test_NoName = X_test[['PRO/NNOR (5)', 'PRO/NNOR (4)', 'PRO/NNOR (3)', 'PRO/NNOR (2)', 'PRO/NNOR (1)', 'PRO/NNOR (0)']]

In [11]:
X_test_NoName.head(3)

,PRO/NNOR (5),PRO/NNOR (4),PRO/NNOR (3),PRO/NNOR (2),PRO/NNOR (1),PRO/NNOR (0)
32,0.0746,0.0151,0.0787,0.1220,0.1634,0.1749
523,-0.0644,0.1676,0.0917,0.1790,0.1310,0.1205
589,0.5476,0.5438,0.5760,0.5428,0.5062,0.4690

In [12]:
print('The accuracy of Random Forest Classifier on testing set:', rfc.score(X_test_NoName, y_test))

The accuracy of Random Forest Classifier on testing set: 0.6280487804878049

In [13]:
testResults = rfc.predict(X_test_NoName)

In [14]:
X_test['預測'] = testResults
X_test['真實'] = y_test

c:\python37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
c:\python37\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [15]:
X_test['不同'] = X_test['預測'] - X_test['真實']

c:\python37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [16]:
X_test.loc[X_test['不同'] != 0]

,公司,PRO/NNOR (5),PRO/NNOR (4),PRO/NNOR (3),PRO/NNOR (2),PRO/NNOR (1),PRO/NNOR (0),預測,真實,不同
589,6464 台數科,0.5476,0.5438,0.5760,0.5428,0.5062,0.4690,0,1,-1
340,2506 太設,0.0459,-0.0527,0.1511,0.2727,0.1968,0.1958,0,1,-1
611,9110 越南控-DR,0.1093,0.0776,0.0670,0.0723,0.1181,0.0647,1,0,1
193,1906 寶隆,0.0639,0.0838,0.0530,0.1165,0.1275,0.1317,1,0,1
159,1617 榮星,0.0372,0.0835,0.0413,0.0479,0.0653,0.0840,1,0,1
...,...,...,...,...,...,...,...,...,...,...
77,1443 立益,-0.0409,0.0701,0.0208,-0.0446,0.0066,-0.0321,1,0,1
615,9902 台火,0.0575,0.1162,0.1674,0.4305,0.3682,0.4255,0,1,-1
240,2101 南港,0.2060,0.2389,0.2326,0.1614,0.1690,0.2404,0,1,-1
150,1613 台一,-0.0188,0.0288,0.0323,0.0261,0.0245,0.0055,1,0,1
210,2013 中鋼構,0.0711,0.0609,0.0684,0.0875,0.0941,0.0805,1,0,1

In [17]:
X_test.loc[X_test['不同'] == 0]

,公司,PRO/NNOR (5),PRO/NNOR (4),PRO/NNOR (3),PRO/NNOR (2),PRO/NNOR (1),PRO/NNOR (0),預測,真實,不同
32,1306 合發,0.0746,0.0151,0.0787,0.1220,0.1634,0.1749,1,1,0
523,3413 京鼎,-0.0644,0.1676,0.0917,0.1790,0.1310,0.1205,0,0,0
306,2435 台路,0.1922,0.1508,0.1397,0.0404,0.0321,-0.0159,1,1,0
529,3622 洋華,0.0000,0.2661,0.2438,0.1890,0.2789,0.3550,0,0,0
171,1802 台玻,0.3380,0.3712,0.3795,0.4090,0.3066,0.2851,0,0,0
...,...,...,...,...,...,...,...,...,...,...
506,3056 總太,0.3428,0.3259,0.2817,0.2793,0.2951,0.2890,0,0,0
68,1438 裕豐,0.0037,0.0104,0.0057,0.2341,0.5114,0.4801,0,0,0
116,1602 太電,0.0786,0.0944,0.0979,0.0644,0.0037,0.1109,1,1,0
286,2371 大同,0.1311,0.0997,0.0275,0.0513,0.0503,0.0454,1,1,0
207,2007 燁興,0.0487,0.1021,0.0977,0.1005,0.0301,0.0919,1,1,0

In [25]:
# Extract single tree
estimator_limited = rfc.estimators_[9]

from sklearn.tree import export_graphviz
export_graphviz(estimator_limited, out_file='tree_limited.dot', feature_names = X_train_NoName.columns,
                class_names = [str(i) for i in y_test.unique()],
                rounded = True, proportion = False, precision = 2, filled = True)

In [21]:
from IPython.display import Image
Image(filename = 'tree_limited.png')